name: Continuous Integration
on:
  push:
    branches:
      - main
jobs:
  zip:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: montudor/action-zip@v1
        with:
          args: zip -qq -r ui.zip main.py requirements.txt run.sh
      - uses: actions/upload-artifact@v2
        with:
          name: ui.zip
